wordpress:
    image: wordpress-image
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "80:80"
mariadb:
    image: my-mariadb
    ports:
     - "3306:3306"

