wordpress:
    image: wordpress-image
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "80:80"
mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"

